application: my-petmeds
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /
  script: pet_controller.app
- url: /create
  script: pet_controller.app
  login: required
- url: /info
  script: pet_controller.app
  login: required
- url: /on_create
  script: pet_controller.app
  login: required
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]